#!/bin/sh

# Copyright 2018 Andrew Clemons
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# shellcheck disable=SC2034
print_divider() { for divider in $(seq 1 "$1") ; do printf "%s" "$2" ; done ; printf "\n" ; }

if [ "$#" -eq 0 ] ; then
  SEQSTART=1
  SEQEND=1
elif [ "$#" -eq 1 ] && [ "x$1" != "x-h" ] ; then
  SEQSTART="$1"
  SEQEND="$1"
else
 cat << EOF
Usage: run [day#]

Runs all the puzzles or optionally the puzzle for the given day

Examples:
  ./run
  ./run 4
EOF

  exit 1
fi

for i in $(seq "$SEQSTART" "$SEQEND") ; do
  day="$(printf "day%02d\\n" "$i")"

  (

    print_divider 72 "="
    printf "%s\\n" "$day"

    cd "$day"

    mvn clean install > /dev/null 2>&1
    <input java -jar "target/$day-1.0-SNAPSHOT.jar"

    print_divider 72 "="
    printf "\n"
  )
done
